apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/larsks/argocd-sync-issue.git
    targetRevision: HEAD
    path: lib/olm/overlays/default
  destination:
    server: https://kubernetes.default.svc
    namespace: olm
