apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/larsks/argocd-sync-issue.git
    targetRevision: HEAD
    path: lib/external-secrets/overlays/with-annotation
  destination:
    server: https://kubernetes.default.svc
    namespace: operators
